libs:
  hiaricl_root: "libs/HiARICL"
  bot_root: "libs/buffer-of-thought-llm"
data:
  raw: "data/raw"
  interim: "data/interim"
  processed: "data/processed"
outputs:
  runs: "outputs/runs"
  artifacts: "outputs/artifacts"
